# Generated by Django 5.2.7 on 2025-11-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
